name: ESPHome LVGL (YAML)
sources:
  type: git
  location:
    origin: https://github.com/sverdlyuk/Lilka-ESPHome
short_description: ESPHome конфігурація для Lilka з підтримкою LVGL графічного фреймворку
description: "@DESCRIPTION.md"
author: "@sverdlyuk"
license: MIT License
keira_version: 1.0.0
icon: image.png
screenshots:
  - image0.png
  - image1.png
  - image2.png
  
